apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
    namespace: database
type: OPAQUE
data:
    # admin
    mongo-root-username: dXNlcm5hbWU=
    # pass
    mongo-root-password: cGFzc3dvcmQ=